### ISSUE TITLE
[Bug] Consistent crashing when pressing a back button from a playing video

### ISSUE THREAD

**Issue by Blistic** [ram-on/SkyTube#111]
I'm running version 2.41.  The crash happens consistently and with an identical error log:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: free.rm.skytube.oss, PID: xxxxxxxx
    java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
        at com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(RequestManagerRetriever.java:134)
        at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:102)
        at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:87)
        at com.bumptech.glide.Glide.with(Glide.java:629)
        at free.rm.skytube.gui.businessobjects.SubsAdapter$SubChannelViewHolder.updateInfo(SubsAdapter.java:193)
        at free.rm.skytube.gui.businessobjects.SubsAdapter.onBindViewHolder(SubsAdapter.java:163)
        at free.rm.skytube.gui.businessobjects.SubsAdapter.onBindViewHolder(SubsAdapter.java:42)
        at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6308)
        at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6341)
        at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5287)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5550)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5392)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5388)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2149)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1533)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1496)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:593)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3535)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3264)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3796)
        at android.view.View.layout(View.java:17637)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
        at android.view.View.layout(View.java:17637)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1217)
        at android.view.View.layout(View.java:17637)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:17637)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:17637)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
        at android.view.View.layout(View.java:17637)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:17637)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
        at android.view.View.layout(View.java:17637)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:727)
        at android.view.View.layout(View.java:17637)
E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6338)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
        at android.view.Choreographer.doCallbacks(Choreographer.java:686)
        at android.view.Choreographer.doFrame(Choreographer.java:621)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6124)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:882)
        at com.android.internal.os.ExecInit.main(ExecInit.java:68)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
E/AndroidRuntime: Error reporting crash
    java.lang.RuntimeException: Bad file descriptor
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:615)
        at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:5133)
        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:97)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)

```

**Comment by ram-on** [comment]
Hello @Blistic,

I've committed a fix to that bug yesterday (36131feaf434dc6964e740c16900cbb3b7ee1d91).  Version 2.5 shall soon be released (hopefully by this weekend).

As a result, I'm going to close this issue for now.  If the bug is still present in the next version of SkyTube, please re-open it.

**Comment by Blistic** [comment]
Hi @ram-on sorry I've been away for a while, but I upgraded to version 2.50 from F-Droid and unfortunately the app still seems to crash consistently upon pressing any back button from a video (either android back, or the within-app back button). The traceback appears to be pretty much the same as last time - maybe version 2.5 in F-Droid hasn't got the fix?  I could pull and compile the latest github version to check.

```
06-11 08:42:41.578 14530-14530/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: free.rm.skytube.oss, PID: 14530
                                                   java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
                                                       at com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(RequestManagerRetriever.java:134)
                                                       at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:102)
                                                       at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:87)
                                                       at com.bumptech.glide.Glide.with(Glide.java:629)
                                                       at free.rm.skytube.gui.businessobjects.SubsAdapter$SubChannelViewHolder.updateInfo(SubsAdapter.java:193)
                                                       at free.rm.skytube.gui.businessobjects.SubsAdapter.onBindViewHolder(SubsAdapter.java:163)
                                                       at free.rm.skytube.gui.businessobjects.SubsAdapter.onBindViewHolder(SubsAdapter.java:42)
                                                       at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6356)
                                                       at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6389)
                                                       at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5335)
                                                       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5598)
                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
                                                       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                                                       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
                                                       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
                                                       at android.view.View.layout(View.java:17637)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                       at android.view.View.layout(View.java:17637)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                       at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1217)
                                                       at android.view.View.layout(View.java:17637)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                       at android.view.View.layout(View.java:17637)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                       at android.view.View.layout(View.java:17637)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                       at android.view.View.layout(View.java:17637)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                       at android.view.View.layout(View.java:17637)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                       at android.view.View.layout(View.java:17637)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                       at com.android.internal.policy.DecorView.onLayout(DecorView.java:727)
                                                       at android.view.View.layout(View.java:17637)
06-11 08:42:41.579 14530-14530/? E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6338)
                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                       at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                       at android.os.Handler.handleCallback(Handler.java:751)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6124)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:882)
                                                       at com.android.internal.os.ExecInit.main(ExecInit.java:68)
                                                       at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
                                                       at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
06-11 08:42:41.582 14530-14530/? E/AndroidRuntime: Error reporting crash
                                                   java.lang.RuntimeException: Bad file descriptor
                                                       at android.os.BinderProxy.transactNative(Native Method)
                                                       at android.os.BinderProxy.transact(Binder.java:615)
                                                       at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:5133)
                                                       at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:97)
                                                       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
                                                       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
```

**Comment by Blistic** [comment]
Also, I do not have the ability to re-open this issue and didn't want to create a new one to confused things, so I just left the comment.

**Comment by Blistic** [comment]
@ram-on As an update, I've now compiled from source with the latest commit 62edab8e962bbade66fe94a86c2d80e05b9c5de2 and I still get the above traceback error when pressing the back key.

**Comment by ram-on** [comment]
@Blistic I cannot seem to replicate your crash.

* What Operating System are you using and what version?
* What device are you using?

**Comment by Blistic** [comment]
@ram-on I'm running Android 7.1.2, with CopperheadOS (https://copperhead.co/android/) which is very closely tied to stock android, so I'm surprised it isn't reproducible. The device is a Lexus 5X.

I have fixed the error on my side by following advice I found in the following thread (which also suggests this problem may be common with glide) https://github.com/bumptech/glide/issues/1097, the first response by TWiStErRob.  I tried the first and last suggested method and both fixed the issue, the last is the easiest the diff is this:

```
diff --git a/app/src/main/java/free/rm/skytube/gui/businessobjects/SubsAdapter.java b/app/src/main/java/free/rm/skytube/gui/businessobjects/SubsAdapter.java
index 21d77d9..3fd4229 100644
--- a/app/src/main/java/free/rm/skytube/gui/businessobjects/SubsAdapter.java
+++ b/app/src/main/java/free/rm/skytube/gui/businessobjects/SubsAdapter.java
@@ -190,7 +190,7 @@ public class SubsAdapter extends RecyclerViewAdapterEx<YouTubeChannel, SubsAdapt
    }   
 
    public void updateInfo(YouTubeChannel channel) {
-     Glide.with(getContext())
+     Glide.with(getContext().getApplicationContext())
          .load(channel.getThumbnailNormalUrl())
          .placeholder(R.drawable.channel_thumbnail_default)
          .into(thumbnailImageView);
```

The first was slightly more involved but appears to be the preferred method by TWiStErRob:

```
diff --git a/app/src/main/java/free/rm/skytube/gui/businessobjects/SubsAdapter.java b/app/src/main/java/free/rm/skytube/gui/businessobjects/SubsAdapter.java
index 21d77d9..9503a42 100644
--- a/app/src/main/java/free/rm/skytube/gui/businessobjects/SubsAdapter.java
+++ b/app/src/main/java/free/rm/skytube/gui/businessobjects/SubsAdapter.java
@@ -27,6 +27,7 @@ import android.widget.ImageView;
 import android.widget.TextView;

 import com.bumptech.glide.Glide;
+import com.bumptech.glide.RequestManager;

 import java.util.Iterator;

@@ -154,7 +155,7 @@ public class SubsAdapter extends RecyclerViewAdapterEx<YouTubeChannel, SubsAdapt
  @Override
  public SubChannelViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
    View v = LayoutInflater.from(parent.getContext()).inflate(R.layout.sub_channel, parent, false);
-   return new SubChannelViewHolder(v);
+   return new SubChannelViewHolder(v,Glide.with(parent.getContext()));
  }


@@ -172,13 +173,15 @@ public class SubsAdapter extends RecyclerViewAdapterEx<YouTubeChannel, SubsAdapt
    private TextView      channelNameTextView;
    private View        newVideosNotificationView;
    private YouTubeChannel    channel = null;
+   private RequestManager      glide;

-   public SubChannelViewHolder(View rowView) {
+   public SubChannelViewHolder(View rowView, RequestManager glide) {
      super(rowView);
      thumbnailImageView  = (ImageView) rowView.findViewById(R.id.sub_channel_thumbnail_image_view);
      channelNameTextView = (TextView) rowView.findViewById(R.id.sub_channel_name_text_view);
      newVideosNotificationView = rowView.findViewById(R.id.sub_channel_new_videos_notification);
      channel = null;
+     this.glide = glide;

      rowView.setOnClickListener(new View.OnClickListener() {
        @Override
@@ -190,11 +193,12 @@ public class SubsAdapter extends RecyclerViewAdapterEx<YouTubeChannel, SubsAdapt
    }

    public void updateInfo(YouTubeChannel channel) {
-     Glide.with(getContext())
-         .load(channel.getThumbnailNormalUrl())
+
+     glide.load(channel.getThumbnailNormalUrl())
          .placeholder(R.drawable.channel_thumbnail_default)
          .into(thumbnailImageView);

+
      channelNameTextView.setText(channel.getTitle());
      newVideosNotificationView.setVisibility(channel.newVideosSinceLastVisit() ? View.VISIBLE : View.INVISIBLE);
      this.channel = channel;
```
If it would be helpful I could also make a pull request with these changes.

**Comment by ram-on** [comment]
@Blistic I prefer the first one as it is simpler.  Please do a pull request.
