### ISSUE TITLE
Window leaked error

### ISSUE THREAD

**Issue by okan35** [ram-on/SkyTube#252]
When I play a video and press back button I get the following error output. If someone can also confirm this, I will work on it to fix it.

`02-21 16:15:08.433 32074-32074/free.rm.skytube.extra E/WindowManager: android.view.WindowLeaked: Activity free.rm.skytube.gui.activities.YouTubePlayerActivity has leaked window DecorView@f03fa3a[] that was originally added here
                                                                          at android.view.ViewRootImpl.<init>(ViewRootImpl.java:489)
                                                                          at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:350)
                                                                          at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
                                                                          at android.widget.MediaController.show(MediaController.java:364)
                                                                          at free.rm.skytube.gui.fragments.YouTubePlayerFragment.showHud(YouTubePlayerFragment.java:579)
                                                                          at free.rm.skytube.gui.fragments.YouTubePlayerFragment.onPrepared(YouTubePlayerFragment.java:499)
                                                                          at android.widget.VideoView$2.onPrepared(VideoView.java:485)
                                                                          at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:3220)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                          at android.os.Looper.loop(Looper.java:251)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6563)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)`

**Comment by ram-on** [comment]
Hi @okan35 , I'm not getting that exception.  Is the app crashing?  It would be nice if that error is fixed though.

**Comment by atomjack** [comment]
I see that exception sometimes, but it never crashes the app.

**Comment by okan35** [comment]
The app does not crash but the exception is still there.

**Comment by ram-on** [comment]
Hi @okan35.  Don't bother fixing this as YouTubePlayerFragment is now deprecated and is going to be replaced by YouTubePlayerFragmentv2 (exoplayer).
