### ISSUE TITLE
Google api limit problem

### ISSUE THREAD

**Issue by okan35** [ram-on/SkyTube#272]
@ram-on This is the first time I encounter this problem. I believe this is something new, have you ever had this as it does not let me open the app and test the features, all I get from app is a white screen with no response and loads of error messages similar to this.

`03-23 19:30:09.199 9776-9802/free.rm.skytube.extra E/GetChannelsDetails: Error has occurred while getting channels info
                                                                         com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
                                                                         {
                                                                           "code": 403,
                                                                           "errors": [
                                                                             {
                                                                               "domain": "usageLimits",
                                                                               "message": "Daily Limit Exceeded. The quota will be reset at midnight Pacific Time (PT). You may monitor your quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/youtube.googleapis.com/quotas?project=102659752285",
                                                                               "reason": "dailyLimitExceeded",
                                                                               "extendedHelp": "https://console.developers.google.com/apis/api/youtube.googleapis.com/quotas?project=102659752285"
                                                                             }
                                                                           ],
                                                                           "message": "Daily Limit Exceeded. The quota will be reset at midnight Pacific Time (PT). You may monitor your quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/youtube.googleapis.com/quotas?project=102659752285"
                                                                         }
                                                                             at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
                                                                             at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
                                                                             at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
                                                                             at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1065)
                                                                             at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
                                                                             at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
                                                                             at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
                                                                             at free.rm.skytube.businessobjects.YouTube.GetChannelsDetails.getYouTubeChannels(GetChannelsDetails.java:170)
                                                                             at free.rm.skytube.businessobjects.YouTube.GetChannelsDetails.getYouTubeChannels(GetChannelsDetails.java:76)
                                                                             at free.rm.skytube.businessobjects.db.SubscriptionsDb.getSubscribedChannels(SubscriptionsDb.java:180)
                                                                             at free.rm.skytube.businessobjects.db.SubscriptionsDb.getSubscribedChannels(SubscriptionsDb.java:149)
                                                                             at free.rm.skytube.businessobjects.db.Tasks.GetSubscribedChannelsTask.doInBackground(GetSubscribedChannelsTask.java:62)
                                                                             at free.rm.skytube.businessobjects.db.Tasks.GetSubscribedChannelsTask.doInBackground(GetSubscribedChannelsTask.java:36)
                                                                             at android.os.AsyncTask$2.call(AsyncTask.java:333)
                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                             at java.lang.Thread.run(Thread.java:764)`

**Comment by ram-on** [comment]
@okan35 Yeah, someone is performing a DOS attack on the API key.  A DOS attack on an open-source project is unbelievable and just shows how some people are just without any morals.

Google provides a way to mitigate such attacks, although they are not foolproof as the keys are made public.  I've tested those and seems to be working.  Will release an emergency fix tomorrow.

**Comment by okan35** [comment]
That is unbelievable. Who could do such thing, why would even someone do this. I mean that person should have a really low life, really.  

Hope the fix is easy and quick.

**Comment by ram-on** [comment]
I've just placed controls in place and published an emergency fix.  Will see how it goes.

**Comment by okan35** [comment]
Thanks I will check it soon.

**Comment by atomjack** [comment]
@ram-on Did you ever get in touch with FDroid about getting their SHA1 signing-certificate fingerprint so you could lock the API keys down to only be used with the app? (Along with your own signing-certificate)

**Comment by ram-on** [comment]
@atomjack Yeah the keys for v2.82 are now using the certificate fingerprint although to be quite honest that method is pretty useless as it can be easily spoofed...
