### ISSUE TITLE
Crash when clicking too quickly on screen when launched from external app

### ISSUE THREAD

**Issue by atomjack** [ram-on/SkyTube#34]
When you choose SkyTube as the app to open a YouTube video from an external app, if you click on the screen too quickly, the app crashes, due to it trying to get the title for the video before the video info is loaded. This only happens when YouTubePlayerActivity is launched with an url instead of a YouTubeVideo object. Here is the stack trace(from the master branch):

`FATAL EXCEPTION: main
                                                                    Process: free.rm.skytube.hd, PID: 32264
                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String free.rm.skytube.businessobjects.YouTubeVideo.getTitle()' on a null object reference
                                                                        at free.rm.skytube.gui.fragments.YouTubePlayerFragment.showHud(YouTubePlayerFragment.java:248)
                                                                        at free.rm.skytube.gui.fragments.YouTubePlayerFragment.showOrHideHud(YouTubePlayerFragment.java:237)
                                                                        at free.rm.skytube.gui.fragments.YouTubePlayerFragment.access$000(YouTubePlayerFragment.java:51)
                                                                        at free.rm.skytube.gui.fragments.YouTubePlayerFragment$1.onClick(YouTubePlayerFragment.java:109)
                                                                        at android.view.View.performClick(View.java:5609)
                                                                        at android.view.View$PerformClick.run(View.java:22259)
                                                                        at android.os.Handler.handleCallback(Handler.java:751)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)`

I can fix this, but should it just not show the hud when `youTubeVideo` is null (line 237), or should it not try to show the video title in the hud (line 248)?

Note:I've found to reliably replicate this you should force close the app, then open a video in another app, choosing SkyTube, and immediately start tapping the screen.

**Comment by ram-on** [comment]
Interesting.  We can solve this by initialising the title instance var to an empty string.  What do you think?

**Comment by atomjack** [comment]
Yeah that would probably be the best way to address it.

**Comment by xtj-9182** [comment]
stupid question but isn't this as simple as adding a trivial null check in the line above 
https://github.com/ram-on/SkyTube/blob/master/app/src/main/java/free/rm/skytube/gui/fragments/YouTubePlayerFragment.java#L275

?

**Comment by ram-on** [comment]
Resolved.
