### ISSUE TITLE
Unable to retrieve any video's streams

### ISSUE THREAD

**Issue by atomjack** [ram-on/SkyTube#345]
All of a sudden this morning, any video I try to play results in a Video Playback Error. I did some digging and it looks like the NewPipeExtractor is unable to get the decryption function name. Here's the stack trace:

```09-07 09:10:42.138 25589-25610/free.rm.skytube.oss E/ParseStreamMetaData: An error has occurred while getting streams metadata.  URL=https://www.youtube.com/watch?v=0fLqHxm90mM
    org.schabi.newpipe.extractor.services.youtube.YoutubeStreamExtractor$DecryptException: Could not parse decrypt function 
        at org.schabi.newpipe.extractor.services.youtube.YoutubeStreamExtractor.loadDecryptionCode(YoutubeStreamExtractor.java:712)
        at org.schabi.newpipe.extractor.services.youtube.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:581)
        at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:61)
        at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:240)
        at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:232)
        at free.rm.skytube.businessobjects.YouTube.VideoStream.ParseStreamMetaData.getStreamMetaDataList(ParseStreamMetaData.java:75)
        at free.rm.skytube.businessobjects.YouTube.Tasks.GetVideoStreamTask.doInBackground(GetVideoStreamTask.java:46)
        at free.rm.skytube.businessobjects.YouTube.Tasks.GetVideoStreamTask.doInBackground(GetVideoStreamTask.java:30)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: org.schabi.newpipe.extractor.utils.Parser$RegexException: failed to find pattern "(["\'])signature\1\s*,\s*([a-zA-Z0-9$]+)\(
        at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:58)
        at org.schabi.newpipe.extractor.services.youtube.YoutubeStreamExtractor.loadDecryptionCode(YoutubeStreamExtractor.java:692)
        at org.schabi.newpipe.extractor.services.youtube.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:581) 
        at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:61) 
        at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:240) 
        at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:232) 
        at free.rm.skytube.businessobjects.YouTube.VideoStream.ParseStreamMetaData.getStreamMetaDataList(ParseStreamMetaData.java:75) 
        at free.rm.skytube.businessobjects.YouTube.Tasks.GetVideoStreamTask.doInBackground(GetVideoStreamTask.java:46) 
        at free.rm.skytube.businessobjects.YouTube.Tasks.GetVideoStreamTask.doInBackground(GetVideoStreamTask.java:30) 
        at android.os.AsyncTask$2.call(AsyncTask.java:333) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
```

@ram-on have you ever seen anything like this before, and are you seeing this right now too? Could YouTube have changed something that broke the extractor functionality? Maybe we should post an issue at https://github.com/TeamNewPipe/NewPipeExtractor/ ?

**Comment by swilde** [comment]
Same here.  The issue for NewPipeExtractor already exists: TeamNewPipe/NewPipeExtractor#107

**Comment by Grammost** [comment]
youtube-dl has the same problem: https://github.com/rg3/youtube-dl/issues/17457 
Seems like YouTube has shipped a new obfuscated JS Player.

**Comment by atomjack** [comment]
Ah, it was created after I posted mine. Ok, we'll have to keep an eye on it :)

**Comment by emporeso2** [comment]
Same bug here ! it has nothing to do with skytube but the youtube plugin on kodi work good !

**Comment by gzsombor** [comment]
A fix in newpipeextractor: https://github.com/TeamNewPipe/NewPipeExtractor/pull/108

**Comment by ram-on** [comment]
We'll have to wait until the push the changes to Jitpack.

**Comment by gzsombor** [comment]
Could you try my fix?

**Comment by ram-on** [comment]
@gzsombor Used your solution.  thx

**Comment by ram-on** [comment]
#346

**Comment by mcpeterc** [comment]
Hi. Im having this issue since yesterday in my Honda civic that runs of Android 4.2.2. Is there anything I Can do to fix it? Im able to install apk files If that helps

**Comment by ram-on** [comment]
@mcpeterc Download SkyTube Extra v2.91.  Link:  https://github.com/ram-on/SkyTube/releases/download/v2.91/SkyTube-Extra-2.91.apk
