### ISSUE TITLE
Cannot play restricted videos

### ISSUE THREAD

**Issue by denilsonsa** [ram-on/SkyTube#454]
Using the F-Droid version.

Example: https://www.youtube.com/watch?v=7t0SqerlBA0

See also a related issue on another project: https://github.com/TeamNewPipe/NewPipe/issues/2459

**Comment by gzsombor** [comment]
I can confirm, the error is the same, I see the stack trace in the emulator:
```
07-13 20:58:17.806 7885-7906/free.rm.skytube.oss E/ParseStreamMetaData: An error has occurred while getting streams metadata.  URL=https://www.youtube.com/watch?v=7t0SqerlBA0
    org.schabi.newpipe.extractor.utils.Parser$RegexException: failed to find pattern ""sts"\s*:\s*(\d+)
        at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:71)
        at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:61)
        at org.schabi.newpipe.extractor.utils.Parser.matchGroup1(Parser.java:52)
        at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getEmbeddedInfo(YoutubeStreamExtractor.java:690)
        at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:600)
        at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:52)
        at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:63)
        at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:59)
        at free.rm.skytube.businessobjects.YouTube.VideoStream.ParseStreamMetaData.getStreamMetaDataList(ParseStreamMetaData.java:72)
        at free.rm.skytube.businessobjects.YouTube.Tasks.GetVideoStreamTask.doInBackground(GetVideoStreamTask.java:45)
        at free.rm.skytube.businessobjects.YouTube.Tasks.GetVideoStreamTask.doInBackground(GetVideoStreamTask.java:30)
        at android.os.AsyncTask$2.call(AsyncTask.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
```

**Comment by gzsombor** [comment]
[2.961](https://github.com/ram-on/SkyTube/releases/tag/v2.961) contains the fix for this bug.
