### ISSUE TITLE
[bug] configure channel blocking at the subscribe page leading to fatal crash

### ISSUE THREAD

**Issue by tingsu** [ram-on/SkyTube#571]
- I have searched the history issue list, and have not found a similar bug. 

- The bug was found in the latest release version 2.965 and also the previous version 2.964, and were reproduciable on both a Google Plxel 3 and an Android emulator 6.0 device

- Bug: go to the subscribe page of an video, and try to configure blocking channels, the app will crash

- Reproducing video 

![SkyTube-Extra-2 965-issue-crash-emulator-6 0](https://user-images.githubusercontent.com/3156978/65817168-4cef2b80-e204-11e9-8780-e8af461ad6ff.gif)

-Crash stack (from the latest release version 2.965)

```
 FATAL EXCEPTION: main
 Process: free.rm.skytube.extra, PID: 28389
 java.lang.IllegalStateException: Fragment ChannelPlaylistsFragment{6a9a89 (7007e6d1-d926-4d60-bb1e-2aa7fcda47e7)} is not currently in the FragmentManager
 	at androidx.fragment.app.FragmentManagerImpl.putFragment(FragmentManagerImpl.java:350)
 	at free.rm.skytube.gui.fragments.ChannelBrowserFragment.onSaveInstanceState(ChannelBrowserFragment.java:185)
 	at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:2766)
 	at androidx.fragment.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManagerImpl.java:2289)
 	at androidx.fragment.app.FragmentManagerImpl.saveAllState(FragmentManagerImpl.java:2348)
 	at androidx.fragment.app.FragmentController.saveAllState(FragmentController.java:151)
 	at androidx.fragment.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:513)
 	at androidx.appcompat.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:533)
 	at free.rm.skytube.gui.activities.BaseActivity.onSaveInstanceState(BaseActivity.java:605)
 	at free.rm.skytube.gui.activities.MainActivity.onSaveInstanceState(MainActivity.java:172)
 	at android.app.Activity.performSaveInstanceState(Activity.java:1298)
 	at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1289)
 	at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4088)
 	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3490)
 	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3550)
 	at android.app.ActivityThread.-wrap20(ActivityThread.java)
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
 	at android.os.Handler.dispatchMessage(Handler.java:102)
 	at android.os.Looper.loop(Looper.java:148)
 	at android.app.ActivityThread.main(ActivityThread.java:5417)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Force finishing activity free.rm.skytube.extra/free.rm.skytube.gui.activities.PreferencesActivity
```

**Comment by tingsu** [comment]
This issue seems always happens if the app cannot download channel information.

**Comment by gzsombor** [comment]
Thanks for the excellent bug report!

**Comment by tingsu** [comment]
Thanks for your quick reply and fix. I personally like this app. Hope it will get better.
