### ISSUE TITLE
DialogUtils.java line 125 - Fatal Exception

### ISSUE THREAD

**Issue by fpasalioglu** [ram-on/SkyTube#580]
I get that fatal error sometimes. What should I do?
#
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Context.getColor(int)' on a null object reference
       at androidx.core.content.ContextCompat.getColor(ContextCompat.java:514)
       at com.afollestad.materialdialogs.util.DialogUtils.getColor(DialogUtils.java:125)
       at com.afollestad.materialdialogs.MaterialDialog$Builder.<init>(MaterialDialog.java:1180)
       at free.rm.skytube.gui.businessobjects.SkyTubeMaterialDialog.<init>(SkyTubeMaterialDialog.java:16)
       at free.rm.skytube.gui.fragments.YouTubePlayerV2Fragment$2.onGetDesiredStreamError(YouTubePlayerV2Fragment.java:419)
       at free.rm.skytube.businessobjects.YouTube.Tasks.GetVideoStreamTask.onPostExecute(GetVideoStreamTask.java:35)
       at free.rm.skytube.businessobjects.YouTube.Tasks.GetVideoStreamTask.onPostExecute(GetVideoStreamTask.java:13)
       at android.os.AsyncTask.finish(AsyncTask.java:660)
       at android.os.AsyncTask.-wrap1(AsyncTask.java)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:677)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)

#

**Comment by gzsombor** [comment]
Could you tell, what did you do? Maybe, you've tried to open a video, and before it could load the stream, you moved away?
