### ISSUE TITLE
An error occurred while executing doInBackground()

### ISSUE THREAD

**Issue by fpasalioglu** [ram-on/SkyTube#586]
When I click any video for watch I get this fatal.

free.rm.skytube.extra E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #5
    Process: free.rm.skytube.extra, PID: 7768
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:399)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: android.database.sqlite.SQLiteException: near ")": syntax error (code 1 SQLITE_ERROR): , while compiling: CREATE TABLE SubsVideos (YouTube_Video_Id TEXT PRIMARY KEY NOT NULL, Channel_Id TEXT NOT NULL, YouTube_Video BLOB, YouTube_Video_Date TIMESTAMP DEFAULT (strftime('%s', 'now')), Retrieval_Timestamp INTEGER, Publish_Timestamp INTEGER,  )
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:986)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:593)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:61)
        at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:33)
        at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1805)
        at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1733)
        at free.rm.skytube.businessobjects.db.SubscriptionsDb.onCreate(SubscriptionsDb.java:90)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:412)
        at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:341)
        at free.rm.skytube.businessobjects.db.SubscriptionsDb.getCachedChannel(SubscriptionsDb.java:632)
        at free.rm.skytube.businessobjects.db.Tasks.GetChannelInfo.getChannelInfoSync(GetChannelInfo.java:65)
        at free.rm.skytube.businessobjects.db.Tasks.GetChannelInfo.doInBackground(GetChannelInfo.java:60)
        at free.rm.skytube.businessobjects.db.Tasks.GetChannelInfo.doInBackground(GetChannelInfo.java:38)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919)

**Comment by gzsombor** [comment]
Thanks for the bug report!
