### ISSUE TITLE
API key can't validate

### ISSUE THREAD

**Issue by ServisOficial** [ram-on/SkyTube#612]
I try to change de API key but say 

> error validating api key

my API key: https://i.ibb.co/k5sM1LD/Screenshot-2019-12-02-Restringir-y-cambia-API-y-servicios-skytube-Consola-de-API-de-Google.png

**Comment by gzsombor** [comment]
I've tried that key, and it fails on the server side:

```
12-02 21:57:06.362  4518  4534 E ValidateYouTubeAPIKey: com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
12-02 21:57:06.362  4518  4534 E ValidateYouTubeAPIKey: {
12-02 21:57:06.362  4518  4534 E ValidateYouTubeAPIKey:   "code": 400,
12-02 21:57:06.362  4518  4534 E ValidateYouTubeAPIKey:   "errors": [
12-02 21:57:06.362  4518  4534 E ValidateYouTubeAPIKey:     {
12-02 21:57:06.362  4518  4534 E ValidateYouTubeAPIKey:       "domain": "usageLimits",
12-02 21:57:06.362  4518  4534 E ValidateYouTubeAPIKey:       "message": "Bad Request",
12-02 21:57:06.362  4518  4534 E ValidateYouTubeAPIKey:       "reason": "keyInvalid"
12-02 21:57:06.362  4518  4534 E ValidateYouTubeAPIKey:     }
12-02 21:57:06.362  4518  4534 E ValidateYouTubeAPIKey:   ],
12-02 21:57:06.362  4518  4534 E ValidateYouTubeAPIKey:   "message": "Bad Request"
12-02 21:57:06.362  4518  4534 E ValidateYouTubeAPIKey: }
12-02 21:57:06.362  4518  4534 E ValidateYouTubeAPIKey:         at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
12-02 21:57:06.362  4518  4534 E ValidateYouTubeAPIKey:         at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
12-02 21:57:06.362  4518  4534 E ValidateYouTubeAPIKey:         at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:451)
12-02 21:57:06.362  4518  4534 E ValidateYouTubeAPIKey:         at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1092)
12-02 21:57:06.362  4518  4534 E ValidateYouTubeAPIKey:         at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:549)
12-02 21:57:06.362  4518  4534 E ValidateYouTubeAPIKey:         at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:482)
12-02 21:57:06.362  4518  4534 E ValidateYouTubeAPIKey:         at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:599)
12-02 21:57:06.362  4518  4534 E ValidateYouTubeAPIKey:         at free.rm.skytube.businessobjects.YouTube.GetFeaturedVideos.getNextVideos(GetFeaturedVideos.java:70)
12-02 21:57:06.362  4518  4534 E ValidateYouTubeAPIKey:         at free.rm.skytube.businessobjects.YouTube.ValidateYouTubeAPIKey.isKeyValid(ValidateYouTubeAPIKey.java:59)
12-02 21:57:06.362  4518  4534 E ValidateYouTubeAPIKey:         at free.rm.skytube.gui.fragments.preferences.OthersPreferenceFragment$ValidateYouTubeAPIKeyTask.doInBackground(OthersPreferenceFragment.java:188)
12-02 21:57:06.362  4518  4534 E ValidateYouTubeAPIKey:         at free.rm.skytube.gui.fragments.preferences.OthersPreferenceFragment$ValidateYouTubeAPIKeyTask.doInBackground(OthersPreferenceFragment.java:175)

```

**Comment by duckbrain** [comment]
I'm also experiencing this. It only gives me the option to generate a "YouTube Data API v3" and some others related to tracking. I can't find documented what API key it expects. Is this the correct version?

**Comment by 13r0ck** [comment]
Yes. 
Go to console.developers.google.com
Create a new project (top left)
In the top bar search for "YouTube Data API v3"
Click"ENABLE"
Click "Create Credentials"

Then you will be brought to a screen saying "add credentials to your project", we aren't going to do that. 
Find the small blue text that says "API key". Click that
Click "Create" at the bottom

Boom. You will be brought to a page with a key in it. Click the copy button next to it. And then email it to yourself so you can copy+paste it into skytube

**Comment by riveravaldez** [comment]
> Yes.
> Go to console.developers.google.com
> Create a new project (top left)
> In the top bar search for "YouTube Data API v3"
> Click"ENABLE"
> Click "Create Credentials"
> 
> Then you will be brought to a screen saying "add credentials to your project", we aren't going to do that.
> Find the small blue text that says "API key". Click that
> Click "Create" at the bottom
> 
> Boom. You will be brought to a page with a key in it. Click the copy button next to it. And then email it to yourself so you can copy+paste it into skytube

Worked perfectly for me. Thanks a lot!
