### ISSUE TITLE
Allow deleting individual search history strings

### ISSUE THREAD

**Issue by Gitoffthelawn** [ram-on/SkyTube#620]
I thought a previous version of SkyTube allowed the user to delete individual search history strings by clicking a little 'x' next to a search history string (without clearing the entire search history).  It's a useful feature, especially if you make a spelling error when searching.

If this was a previous feature, can it be restored?  If it wasn't a previous feature, can you add it?

**Comment by gzsombor** [comment]
Yes, it was a feature which caused the app to halt on older Androids, unfortunately no-one debugged further, I've just quickly disabled the icon

**Comment by Gitoffthelawn** [comment]
Thanks. I thought it was there before!  On what version of Android does it start not having problems?  As a temp kludge, can you just add a version check and enable it on working Android versions?

**Comment by atomjack** [comment]
@gzsombor I just did some research into this, and made a [pull request](https://github.com/ram-on/SkyTube/pull/641) to re-enable the images in the search hints dropdown (one is just an image, the other an image button to delete an entry). I found via [this link](https://stackoverflow.com/questions/38221986/android-vector-drawable-appsrccompat-not-showing-images) that the correct way to use app:srcCompat is to use AppCompat ImageView's and ImageViewButton's. I created an AVD using API 19, and it seems to work fine.

I also created an AVD using API 16 (the lowest I could go), however it crashed immediately on startup (even without my changes), with this in the logcat:

```01-22 09:33:16.133 2653-2676/free.rm.skytube.oss E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
    java.lang.RuntimeException: An error occured while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:299)
        at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
        at java.util.concurrent.FutureTask.run(FutureTask.java:137)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
        at java.lang.Thread.run(Thread.java:856)
     Caused by: java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets
        at com.google.api.client.util.escape.CharEscapers.decodeUriPath(CharEscapers.java:110)
        at com.google.api.client.http.GenericUrl.toPathParts(GenericUrl.java:594)
        at com.google.api.client.http.GenericUrl.<init>(GenericUrl.java:200)
        at com.google.api.client.http.GenericUrl.<init>(GenericUrl.java:177)
        at com.google.api.client.http.GenericUrl.<init>(GenericUrl.java:126)
        at com.google.api.client.http.GenericUrl.<init>(GenericUrl.java:109)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.buildHttpRequestUrl(AbstractGoogleClientRequest.java:395)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.buildHttpRequest(AbstractGoogleClientRequest.java:430)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:549)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:482)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:599)
        at free.rm.skytube.businessobjects.YouTube.GetFeaturedVideos.getNextVideos(GetFeaturedVideos.java:70)
        at free.rm.skytube.businessobjects.YouTube.Tasks.GetYouTubeVideosTask.getNextVideos(GetYouTubeVideosTask.java:117)
        at free.rm.skytube.businessobjects.YouTube.Tasks.GetYouTubeVideosTask.doInBackground(GetYouTubeVideosTask.java:94)
        at free.rm.skytube.businessobjects.YouTube.Tasks.GetYouTubeVideosTask.doInBackground(GetYouTubeVideosTask.java:39)
        at android.os.AsyncTask$2.call(AsyncTask.java:287)
```

Upon further investigation, it looks like the google api's library uses `java.nio.charset.StandardCharsets`, which was introduced in API 19. This is why my API 16 is crashing. We might want to discuss (via another issue?) whether or not to just up the minSdk version to 19.

**Comment by gzsombor** [comment]
Thanks for the investigation. I would have hoped, that Google's libraries were compiled in a way, that these kind of problems were reported during compilation. (Because for other libraries, the build  indeed fails, if I try to use a version, which need newer Android version - for example, we can't use exoplayer 2.10.x, etc)

**Comment by Gitoffthelawn** [comment]
@gzsombor Google writes their own rules when it comes to Google, yet demands a higher standard from everyone else.

I've been disappointed by Google so many times, that now I tend to expect the worst.
