### ISSUE TITLE
Unable to resume activity on ChromecastBaseControllerFragment

### ISSUE THREAD

**Issue by fpasalioglu** [ram-on/SkyTube#655]
When I started a video on Chromecast, the video starts but if I playing another video, app crashes.

Logcat:
java.lang.RuntimeException: Unable to resume activity {free.rm.skytube.gui.activities.YouTubePlayerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void free.rm.skytube.gui.fragments.ChromecastBaseControllerFragment.init(com.google.android.gms.cast.framework.media.RemoteMediaClient)' on a null object reference
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3563)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3603)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2850)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1572)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6364)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void free.rm.skytube.gui.fragments.ChromecastBaseControllerFragment.init(com.google.android.gms.cast.framework.media.RemoteMediaClient)' on a null object reference
        at free.rm.skytube.gui.activities.BaseActivity.onResume(BaseActivity.java:269)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1269)
        at android.app.Activity.performResume(Activity.java:6770)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3534)

**Comment by atomjack** [comment]
Can you answer the following questions?

1) Does this accurately describe what you are doing, and what is happening? 
       You start to play a video on the chromecast, it is playing just fine, but when you tap on a different video to play, while the first is already playing, the app crashes with the above message.

2) What version of Android are you running?
3) Does this happen every single time you do what is described in 1)? Or does it only happen occasionally/rarely/often but not always?

**Comment by fpasalioglu** [comment]
Sorry, it was my fault. Solved.
