### ISSUE TITLE
[Bug] Crash on opening channel from subscribe panel

### ISSUE THREAD

**Issue by xamica** [ram-on/SkyTube#69]
Latest version on F-Droid.
Backtrace:

```

D/AndroidRuntime( 6264): Shutting down VM
W/dalvikvm( 6264): threadid=1: thread exiting with uncaught exception (group=0x419f9ce0)
W/dalvikvm( 6264): threadid=1: uncaught exception occurred
W/System.err( 6264): java.lang.NullPointerException
W/System.err( 6264):    at free.rm.skytube.gui.businessobjects.SubsAdapter.changeChannelNewVideosStatus(SubsAdapter.java:127)
W/System.err( 6264):    at free.rm.skytube.gui.fragments.ChannelBrowserFragment.initViews(ChannelBrowserFragment.java:168)
W/System.err( 6264):    at free.rm.skytube.gui.fragments.ChannelBrowserFragment.onCreateView(ChannelBrowserFragment.java:107)
W/System.err( 6264):    at android.support.v4.app.Fragment.performCreateView(Fragment.java:2087)
W/System.err( 6264):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1113)
W/System.err( 6264):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1295)
W/System.err( 6264):    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
W/System.err( 6264):    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1682)
W/System.err( 6264):    at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:541)
W/System.err( 6264):    at android.os.Handler.handleCallback(Handler.java:808)
W/System.err( 6264):    at android.os.Handler.dispatchMessage(Handler.java:103)
W/System.err( 6264):    at android.os.Looper.loop(Looper.java:193)
W/System.err( 6264):    at android.app.ActivityThread.main(ActivityThread.java:5323)
W/System.err( 6264):    at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err( 6264):    at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err( 6264):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
W/System.err( 6264):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
W/System.err( 6264):    at dalvik.system.NativeStart.main(Native Method)
W/dalvikvm( 6264): threadid=1: calling UncaughtExceptionHandler
E/AndroidRuntime( 6264): FATAL EXCEPTION: main
E/AndroidRuntime( 6264): Process: free.rm.skytube.oss, PID: 6264
E/AndroidRuntime( 6264): java.lang.NullPointerException
E/AndroidRuntime( 6264):        at free.rm.skytube.gui.businessobjects.SubsAdapter.changeChannelNewVideosStatus(SubsAdapter.java:127)
E/AndroidRuntime( 6264):        at free.rm.skytube.gui.fragments.ChannelBrowserFragment.initViews(ChannelBrowserFragment.java:168)
E/AndroidRuntime( 6264):        at free.rm.skytube.gui.fragments.ChannelBrowserFragment.onCreateView(ChannelBrowserFragment.java:107)
E/AndroidRuntime( 6264):        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2087)
E/AndroidRuntime( 6264):        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1113)
E/AndroidRuntime( 6264):        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1295)
E/AndroidRuntime( 6264):        at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
E/AndroidRuntime( 6264):        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1682)
E/AndroidRuntime( 6264):        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:541)
E/AndroidRuntime( 6264):        at android.os.Handler.handleCallback(Handler.java:808)
E/AndroidRuntime( 6264):        at android.os.Handler.dispatchMessage(Handler.java:103)
E/AndroidRuntime( 6264):        at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime( 6264):        at android.app.ActivityThread.main(ActivityThread.java:5323)
E/AndroidRuntime( 6264):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 6264):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 6264):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
E/AndroidRuntime( 6264):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
E/AndroidRuntime( 6264):        at dalvik.system.NativeStart.main(Native Method)

```

**Comment by ram-on** [comment]
Hi, can you please indicate which channel you are trying to open?

**Comment by xamica** [comment]
Almost 50% from my list, too much for channel-specific problem

**Comment by atomjack** [comment]
@xamica, please give some examples. 

@ram-on, if he doesn't, I say close the issue.

**Comment by ram-on** [comment]
This should be solved by now.
