### ISSUE TITLE
Fatal crash - Fragment ChannelBrowserFragment has not been attached yet.

### ISSUE THREAD

**Issue by tingsu** [ram-on/SkyTube#702]
- I have searched the history issue list, and have not found a similar bug. 

- The bug was found in the latest release version 2.971 (SkyTube-Oss-2.971.apk) and also the previous version 2.97, and were reproduciable on both a Google Plxel 3 and an Android emulator 6.0 device

- Repro Steps: 

1. go to the subscribe page of an video, 
2. quickly press the back icon on the top of the page (before the subscribe page finishes the loading)
3. scroll the video list
4. the app crashes

- Reproducing video 

![20200325_113143](https://user-images.githubusercontent.com/3156978/77527641-c9e61f80-6e8c-11ea-9043-08717fee73bb.gif)

-Crash stack (from the latest release version 2.971 (2020-03-23 21:22) )

```
 Process: free.rm.skytube.oss, PID: 4224
 java.lang.IllegalStateException: Fragment ChannelBrowserFragment{ca4270d (6120b9bc-445f-40e4-8384-f5355d9d306f)} has not been attached yet.
 	at androidx.fragment.app.Fragment.getChildFragmentManager(Fragment.java:923)
 	at free.rm.skytube.gui.fragments.ChannelBrowserFragment.initViews(ChannelBrowserFragment.java:202)
 	at free.rm.skytube.gui.fragments.ChannelBrowserFragment.access$400(ChannelBrowserFragment.java:60)
 	at free.rm.skytube.gui.fragments.ChannelBrowserFragment$ProcessChannel.onGetYouTubeChannel(ChannelBrowserFragment.java:267)
 	at free.rm.skytube.businessobjects.db.Tasks.GetChannelInfo.onPostExecute(GetChannelInfo.java:107)
 	at free.rm.skytube.businessobjects.db.Tasks.GetChannelInfo.onPostExecute(GetChannelInfo.java:40)
 	at android.os.AsyncTask.finish(AsyncTask.java:651)
 	at android.os.AsyncTask.-wrap1(AsyncTask.java)
 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
 	at android.os.Handler.dispatchMessage(Handler.java:102)
 	at android.os.Looper.loop(Looper.java:148)
 	at android.app.ActivityThread.main(ActivityThread.java:5417)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```

**Comment by gzsombor** [comment]
Thanks for the detailed crash report, really appreciated!

**Comment by tingsu** [comment]
Thanks for your quick confirmation and fix, @gzsombor ! I will continue to contribute to this app!

**Comment by gzsombor** [comment]
Thanks for the future contributions too! :wink:
