### ISSUE TITLE
Fatal crash - NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference

### ISSUE THREAD

**Issue by tingsu** [ram-on/SkyTube#703]
- I have searched the history issue list, and have not found a similar bug. 

- The bug was found in the version 2.97, and were reproduciable on both a Google Plxel 3 and an Android emulator 6.0 device

- Repro Steps: 

I have the event trace that leads to the crash point, but I have not succeeded to reproduce this. The crash stack indicates this issue related to a background thread, which may explain why it is not easy to reproduce.

Let me know if you need from info from my side, e..g., the event trace. 

-Crash stack (from the latest release version 2.97 (2020-03-23 21:22) )

```
 FATAL EXCEPTION: AsyncTask #2
 Process: free.rm.skytube.extra, PID: 21401
 java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:309)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
       at java.io.StringReader.<init>(StringReader.java:47)
       at org.jsoup.parser.Parser.parse(Parser.java:107)
       at org.jsoup.Jsoup.parse(Jsoup.java:31)
       at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor.getPage(YoutubeChannelExtractor.java:193)
       at free.rm.skytube.businessobjects.YouTube.newpipe.Pager.getNextPage(Pager.java:80)
       at free.rm.skytube.businessobjects.YouTube.NewPipeVideos.getNextVideos(NewPipeVideos.java:56)
       at free.rm.skytube.businessobjects.YouTube.Tasks.GetYouTubeVideosTask.getNextVideos(GetYouTubeVideosTask.java:117)
       at free.rm.skytube.businessobjects.YouTube.Tasks.GetYouTubeVideosTask.doInBackground(GetYouTubeVideosTask.java:94)
       at free.rm.skytube.businessobjects.YouTube.Tasks.GetYouTubeVideosTask.doInBackground(GetYouTubeVideosTask.java:39)
       at android.os.AsyncTask$2.call(AsyncTask.java:295)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       ... 3 more
```

**Comment by gzsombor** [comment]
Thanks for the detailed report!
 The crash comes from the NewPipeExtractor library - from [here](https://github.com/TeamNewPipe/NewPipeExtractor/blob/ff61e28424d4c12cf1ff8a914f38fcbd406f2b17/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeChannelExtractor.java#L193). From the nearly 2 month old v2.970 release, not from the brand new v2.971. NewPipeExtractor scrapes the html and js content of the site, so the library is in a constant flux -  the current version has a very different [code](https://github.com/TeamNewPipe/NewPipeExtractor/blob/65a7eda4464e1ec524328885adea64ebb5737110/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeChannelExtractor.java#L187). Why has it been changed? Maybe the returned content changed ...
So it is impossible to fix this particular crash, the best what I could do, is to improve the exception handling - I mean, to add more 'catch RuntimeException' from NewPipeExtractor to make the app more fault tolerant - in a particular sense.

**Comment by tingsu** [comment]
Thanks for your very quick patch, @gzsombor. I think it is fine to quickly patch this issue by enhancing the exception handling.
