### ISSUE TITLE
SQLiteConstraintException - UNIQUE constraint failed: Bookmarks.YouTube_Video_Id

### ISSUE THREAD

**Issue by tingsu** [ram-on/SkyTube#705]
The error was found in the version 2.97

I am not sure whether this error is important. I observed many times.

```
 Error inserting Order_Index=19 YouTube_Video_Id=VJYpyC1SNPc YouTube_Video=[B@76f33d8
 android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: Bookmarks.YouTube_Video_Id (code 1555)
 	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
 	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:780)
 	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
 	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
 	at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1471)
 	at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1341)
 	at free.rm.skytube.businessobjects.db.BookmarksDb.add(BookmarksDb.java:103)
 	at free.rm.skytube.businessobjects.YouTube.POJOs.YouTubeVideo.bookmarkVideo(YouTubeVideo.java:487)
 	at free.rm.skytube.businessobjects.YouTube.POJOs.YouTubeVideo.bookmarkVideo(YouTubeVideo.java:483)
 	at free.rm.skytube.gui.activities.ShareBookmarkActivity.lambda$onCreate$0$ShareBookmarkActivity(ShareBookmarkActivity.java:28)
 	at free.rm.skytube.gui.activities.-$$Lambda$ShareBookmarkActivity$ERngxTG_JavJqWVh6QBIrJ7Wlho.onYouTubeVideo(lambda)
 	at free.rm.skytube.businessobjects.GetVideoDetailsTask.onPostExecute(GetVideoDetailsTask.java:85)
 	at free.rm.skytube.businessobjects.GetVideoDetailsTask.onPostExecute(GetVideoDetailsTask.java:21)
 	at android.os.AsyncTask.finish(AsyncTask.java:651)
 	at android.os.AsyncTask.-wrap1(AsyncTask.java)
 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
 	at android.os.Handler.dispatchMessage(Handler.java:102)
 	at android.os.Looper.loop(Looper.java:148)
 	at android.app.ActivityThread.main(ActivityThread.java:5417)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by gzsombor** [comment]
You used the "bookmark a video" from another app. The video data was retrieved, and the app tried to save this into it's local db, however there is an SQL constraint which prevents the same video to be inserted multiple times, in this case an exception was thrown, and catched in SQLiteDatabase.insert(...), and logged, without crashing the app. The app is reporting, that it couldn't bookmark the video - which is true, but a bit misleading, as the bookmark is already exists.

**Comment by tingsu** [comment]
Thanks for the detailed explanation. I got that. Yes, you are right, this exception in fact was caught.
