### ISSUE TITLE
Fatal crash - IllegalArgumentException: Failed to find configured root that contains...

### ISSUE THREAD

**Issue by tingsu** [ram-on/SkyTube#712]
This exception issue was found in the version 2.97. I fail to come up with a short event trace to help reproduce due to the original logged trace is too long ... 

But the issue was triggered when clicking ``Open with`` from the menu (see the last screenshot of event trace below). Let me know if you need more info from my side.

<img src="https://user-images.githubusercontent.com/3156978/77823628-da9ccc80-70fc-11ea-9a56-82b945fef124.png" width="400" height="600" />

One stack trace:
```
 FATAL EXCEPTION: main
 Process: free.rm.skytube.extra, PID: 4263
 java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/1A0F-2A1A/Android/data/com.google.android.gms/files/CsK6NYCA0s8 BẢO QUAY XE LÊ BẢO Official.mp4
 	at androidx.core.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:744)
 	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:418)
 	at free.rm.skytube.businessobjects.YouTube.POJOs.YouTubeVideo.playVideoExternally(YouTubeVideo.java:632)
 	at free.rm.skytube.gui.businessobjects.adapters.GridViewHolder.lambda$onOptionsButtonClick$3$GridViewHolder(GridViewHolder.java:205)
 	at free.rm.skytube.gui.businessobjects.adapters.-$$Lambda$GridViewHolder$pfeOfyiQWeUaMuipGX7ZrJS4xQs.onMenuItemClick(lambda)
 	at androidx.appcompat.widget.PopupMenu$1.onMenuItemSelected(PopupMenu.java:113)
 	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
 	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
 	at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
 	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
 	at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3042)
 	at android.widget.AbsListView$3.run(AbsListView.java:3879)
 	at android.os.Handler.handleCallback(Handler.java:739)
 	at android.os.Handler.dispatchMessage(Handler.java:95)
 	at android.os.Looper.loop(Looper.java:148)
 	at android.app.ActivityThread.main(ActivityThread.java:5417)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

Another stack trace with similar root cause:
```
 FATAL EXCEPTION: main
 Process: free.rm.skytube.extra, PID: 25675
 java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/1A0F-2A1A/Android/data/com.google.android.gms/files/CsK6NYCA0s8 BẢO QUAY XE LÊ BẢO Official.mp4
 	at androidx.core.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:744)
 	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:418)
 	at free.rm.skytube.businessobjects.YouTube.POJOs.YouTubeVideo.playVideoExternally(YouTubeVideo.java:632)
 	at free.rm.skytube.gui.fragments.YouTubePlayerV2Fragment.onOptionsItemSelected(YouTubePlayerV2Fragment.java:531)
 	at androidx.fragment.app.Fragment.performOptionsItemSelected(Fragment.java:2733)
 	at androidx.fragment.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManagerImpl.java:2758)
 	at androidx.fragment.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:411)
 	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:390)
 	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:219)
 	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
 	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
 	at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:64)
 	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
 	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
 	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
 	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
 	at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
 	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
 	at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3042)
 	at android.widget.AbsListView$3.run(AbsListView.java:3879)
 	at android.os.Handler.handleCallback(Handler.java:739)
 	at android.os.Handler.dispatchMessage(Handler.java:95)
 	at android.os.Looper.loop(Looper.java:148)
 	at android.app.ActivityThread.main(ActivityThread.java:5417)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by gzsombor** [comment]
Interesting, as well. What Android version do you use? I've already saw that, with Android 8 (or later), writing, or modifying the external storage fails - sometimes the download manager couldn't download files - in #529 , sometimes SkyTube cant delete files from there - in #681.
 This /storage/1A0F-2A1A/Android/data/com.google.android.gms/files/ path looks like it's on an external storage, isn't it? Or it's the default path?

**Comment by tingsu** [comment]
I am using Android 6.0 (SDK version 23). Yes, you are right, the path ``/storage/1A0F-2A1A/Android/data/com.google.android.gms/files/`` is on an SDcard (i.e., an external storage).  This  is the first time I saw this issue.

**Comment by gzsombor** [comment]
It's unclear why this happens, but at least, we shouldn't stop the program, so I've added a catch block, until better understanding gained someone ...
