### ISSUE TITLE
Crash when updating youtube channels

### ISSUE THREAD

**Issue by inrepublica** [ram-on/SkyTube#827]
I have a crash of the application when updating the youtube channels.

Don't have this problem with previous version.

Do you have a path to the log file?

**Comment by malloy139** [comment]
I have the same problem

**Comment by gzsombor** [comment]
I don't know if you could access any log files on your device - without being root or hacks. However, if you have adb (Android SDK) installed on your machine, you can run '..../android-sdk-linux_x86/platform-tools/adb logcat' to see all the logs.
'

**Comment by inrepublica** [comment]
The crash come when updating 73/94 channel -> https://inrepublica.fr/bozon/?f=15f9c9b14bce7e

**Comment by inrepublica** [comment]
With my One Plus 7 Pro in dev options I have dump log options:
`
Process: free.rm.skytube.extra
PID: 26864
UID: 10390
Flags: 0x30d8be44
Package: free.rm.skytube.extra v34 (2.974)
Foreground: No
Build: OnePlus/OnePlus7Pro/OnePlus7Pro:10/QKQ1.190716.003/2007240000:user/release-keys

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:399)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
	at free.rm.skytube.businessobjects.YouTube.Tasks.GetBulkSubscriptionVideosTask$1.doInBackground(GetBulkSubscriptionVideosTask.java:98)
	at free.rm.skytube.businessobjects.YouTube.Tasks.GetBulkSubscriptionVideosTask$1.doInBackground(GetBulkSubscriptionVideosTask.java:82)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
`

**Comment by gzsombor** [comment]
Thanks, I will fix and do a release

**Comment by gzsombor** [comment]
Done, I hope, this time, I haven't screwed anything

**Comment by inrepublica** [comment]
2.975 works perfectly, thank you very much to you.
