### ISSUE TITLE
crash - IllegalArgumentException: You cannot start a load for a destroyed activity

### ISSUE THREAD

**Issue by virat-shukla** [ram-on/SkyTube#94]
03-30 17:01:57.380 4155-4155/free.rm.skytube.extra E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: free.rm.skytube.extra, PID: 4155
                                                                     java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
                                                                         at com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(RequestManagerRetriever.java:134)
                                                                         at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:102)
                                                                         at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:87)
                                                                         at com.bumptech.glide.Glide.with(Glide.java:629)
                                                                         at free.rm.skytube.gui.businessobjects.GridViewHolder.updateViewsData(GridViewHolder.java:104)
                                                                         at free.rm.skytube.gui.businessobjects.GridViewHolder.updateInfo(GridViewHolder.java:87)
                                                                         at free.rm.skytube.gui.businessobjects.VideoGridAdapter.onBindViewHolder(VideoGridAdapter.java:171)
                                                                         at free.rm.skytube.gui.businessobjects.VideoGridAdapter.onBindViewHolder(VideoGridAdapter.java:40)
                                                                         at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6308)
                                                                         at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6341)
                                                                         at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5287)
                                                                         at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5550)
                                                                         at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5392)
                                                                         at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5388)
                                                                         at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2149)
                                                                         at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
                                                                         at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1496)
                                                                         at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:593)
                                                                         at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                                         at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3535)
                                                                         at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3264)
                                                                         at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3796)
                                                                         at android.view.View.layout(View.java:17641)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                         at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:636)
                                                                         at android.view.View.layout(View.java:17641)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                         at android.view.View.layout(View.java:17641)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                         at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1795)
                                                                         at android.view.View.layout(View.java:17641)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                         at android.view.View.layout(View.java:17641)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                         at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                         at android.view.View.layout(View.java:17641)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                         at android.view.View.layout(View.java:17641)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                         at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1193)
                                                                         at android.view.View.layout(View.java:17641)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                         at android.view.View.layout(View.java:17641)
03-30 17:01:57.381 4155-4155/free.rm.skytube.extra E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                         at android.view.View.layout(View.java:17641)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                         at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                         at android.view.View.layout(View.java:17641)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                         at android.view.View.layout(View.java:17641)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                         at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                         at android.view.View.layout(View.java:17641)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                         at com.android.internal.policy.DecorView.onLayout(DecorView.java:726)
                                                                         at android.view.View.layout(View.java:17641)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                         at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
                                                                         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
                                                                         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6343)
                                                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                         at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                         at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                         at android.os.Handler.handleCallback(Handler.java:751)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6126)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by ram-on** [comment]
Can you pls indicate how this exception was triggered?  Do you have any procedure how to replicate it?

**Comment by atomjack** [comment]
By the way, I am getting this as well, on `master`, using the OSS variant (it also happens with the Extra Variant and my Chromecast branch). It seems to have something to do with Glide. For me, I start up the app, and everything is fine. Hit the back button, to exit the app, back to my homescreen, and then launch the app again, and I get the crash. I will note that my stacktrace is slightly different, though:

```
05-08 10:16:12.387 14354-14354/free.rm.skytube.oss E/AndroidRuntime: FATAL EXCEPTION: main
Process: free.rm.skytube.oss, PID: 14354
java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
    at com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(RequestManagerRetriever.java:134)
    at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:102)
    at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:87)
    at com.bumptech.glide.Glide.with(Glide.java:629)
    at free.rm.skytube.gui.businessobjects.SubsAdapter$SubChannelViewHolder.updateInfo(SubsAdapter.java:193)
    at free.rm.skytube.gui.businessobjects.SubsAdapter.onBindViewHolder(SubsAdapter.java:163)
    at free.rm.skytube.gui.businessobjects.SubsAdapter.onBindViewHolder(SubsAdapter.java:42)
    at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6308)
    at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6341)
    at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5287)
    at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5550)
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5392)
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5388)
    at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2149)
    at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1533)
    at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1496)
    at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:593)
    at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3535)
    at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3264)
    at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3796)
    at android.view.View.layout(View.java:17641)
    at android.view.ViewGroup.layout(ViewGroup.java:5575)
    at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
    at android.view.View.layout(View.java:17641)
    at android.view.ViewGroup.layout(ViewGroup.java:5575)
    at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1217)
    at android.view.View.layout(View.java:17641)
    at android.view.ViewGroup.layout(ViewGroup.java:5575)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    at android.view.View.layout(View.java:17641)
    at android.view.ViewGroup.layout(ViewGroup.java:5575)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    at android.view.View.layout(View.java:17641)
    at android.view.ViewGroup.layout(ViewGroup.java:5575)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
    at android.view.View.layout(View.java:17641)
    at android.view.ViewGroup.layout(ViewGroup.java:5575)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    at android.view.View.layout(View.java:17641)
    at android.view.ViewGroup.layout(ViewGroup.java:5575)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
    at android.view.View.layout(View.java:17641)
    at android.view.ViewGroup.layout(ViewGroup.java:5575)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    at com.android.internal.policy.DecorView.onLayout(DecorView.java:728)
    at android.view.View.layout(View.java:17641)
05-08 10:16:12.387 14354-14354/free.rm.skytube.oss E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5575)
    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6343)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
    at android.view.Choreographer.doCallbacks(Choreographer.java:686)
    at android.view.Choreographer.doFrame(Choreographer.java:621)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6176)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
```

The line in SkyTube code that actually causes the crash is in `SubsAdapter.java`, line 193:

```
Glide.with(getContext())
					.load(channel.getThumbnailNormalUrl())
					.placeholder(R.drawable.channel_thumbnail_default)
					.into(thumbnailImageView);
```

Looking at OP's stack trace, I see a similar Glide call on line 95 (his stack trace has a different line number, probably due to this file being updated since whatever release he's running):
```
Glide.with(context)
				.load(video.getThumbnailUrl())
				.placeholder(R.drawable.thumbnail_default)
				.into(thumbnailImageView);
```

I did a google search on the error, and came across this Glide issue: https://github.com/bumptech/glide/issues/975

I'm not really familiar with what Glide is doing (images or something:), so I figured you @ram-on might wanna try to tackle this. I'll note I can make this happen *every time* I re-launch the app after exiting (but you have to use the back button - using the home button doesn't cause it to trigger).

**Comment by ram-on** [comment]
@atomjack good catch.  I'm triggering that as well when using your approach.  I'll take a look.

**Comment by ram-on** [comment]
Resolved.
